language: android
jdk: oraclejdk8
sudo: true

android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - build-tools-25.0.2
    - android-25
  licenses:
    - android-sdk-license-.+

script:
- ./gradlew clean test
